version: "2"
services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  
  telegram-bot:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - API_TOKEN=${API_TOKEN}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - ADMIN_ID=${ADMIN_ID}

volumes:
  postgres_data:
